# Disable the "core" redis plugins
disablePlugins:
  - lando-redis

# Make sure we are dogfooding this plugin for testing purposes
plugins:
  "@lando/redis": /home/runner/work/redis/redis

# Disable metrics reporting
stats:
  - report: false
    url: https://metrics.lando.dev
